title:            Meniny
description:      This is my very own blog which shares skills.
url:              http://www.meniny.cn/
paginate:         10

pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# Theme specific settings
theme:            b
signoff:          Meniny
facebook_appid:   
google_analytics: 
disqus_shortname: 

owner:
  name:           Meniny
  avatar:         'https://secure.gravatar.com/avatar/afd3cc3e385d754183336c859d9e694a?s=420&d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-user-420.png'
  bio:            'Software developer on PC, Linux, ARM and iOS platform. Crafty. Blogger. Traveller. Big fan of Apple. Love of color. Doggies are my fave.'

links: 
  - name:         Home
    url:          /
  - name:         Categories
    url:          /categories
  - name:         About
    url:          /about
  - name:         Email
    url:          Meniny@qq.com
  - name:         GitHub
    url:          http://github.com/Meniny