markdown: redcarpet
permalink: /:categories/:title.html
url: meniny.cn
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: meniny.cn
title: Meniny's Blog
description: iOS, OS X, Linux, UNIX, Reading...
author: Meniny
email: meniny#qq.com
github: Meniny

config:
  js_dir:
  img_dir:
  css_dir:
