markdown: redcarpet
permalink: /:categories/:title.html
baseurl: /
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: meniny.cn
title: Meniny's Blog
description: This is my very own Blog which is collects and shares IT skills. I hope you like it.
author: Meniny
email: meniny#qq.com
github: Meniny

config:
  js_dir:
  img_dir:
  css_dir:
