title:            Meniny
description:      This is my very own blog which shares skills.
url:              http://www.meniny.cn/
paginate:         10

pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# Theme specific settings
theme:            b
signoff:          Mu-An
#facebook_appid:   
#google_analytics: 
#disqus_shortname: 

owner:
  name:           Meniny
  avatar:         'http://images.apple.com/support/assets/images/home/2015/imac_2x.png'
  bio:            'Software developer on PC, Linux, ARM and iOS platform. Crafty. Blogger. Traveller. Big fan of Apple. Love of color. Doggies are my fave.'

links: 
  - name:         Home
    url:          /
  - name:         Categories
    url:          /categories
  - name:         About
    url:          /about
  - name:         Email
    url:          Meniny:._.@qq.com
  - name:         GitHub
    url:          http://github.com/Meniny