name: Meniny
url: http://www.meniny.cn/
description: This is my very own Blog which shares skills. I hope you like it.

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['Gemfile.lock', 'Gemfile', 'Rakefile']
